baseURL = "/"
languageCode = "en-us"
title = "Amaya Nogales Gómez"
theme = "hallo"


[Author]
    name = "Amaya Nogales Gómez"
    
    
[params]
greeting = "Hola"
[[params.links]]
	iconset = "fas"
	icon = "paper-plane"
	title = "e-mail"
	url = "mailto:amaya.nogales-gomez@i3s.unice.fr"
[[params.links]]
	iconset = "fas"
	icon = "graduation-cap"
	title = "Google Scholar"
	url = "https://scholar.google.com/citations?user=VlbI1uIAAAAJ&hl=es"
[[params.links]]
	icon = "linkedin-in"
	title = "LinkedIn"
	url = "https://www.linkedin.com/in/amaya-nogales-gomez"

	
      
[params.colors]
	background = "#EAAC9D"
	foreground = "#edf7ff"
	hover = "#ffba82"	
	
